-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 00:44:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET utf8 ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Book` (
  `GoogleBooksID` CHAR(12) NOT NULL,
  PRIMARY KEY (`GoogleBooksID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`UserProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`UserProfile` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(70) NOT NULL,
  `Bio` VARCHAR(300) NULL,
  `Profile_Picture` VARCHAR(45) NULL,
  `FavAuthor` VARCHAR(70) NULL,
  `FavGenre` VARCHAR(30) NULL,
  `IsAuthor` TINYINT NULL,
  `FavBook` CHAR(12) NULL,
  PRIMARY KEY (`ID`),
  INDEX `Fk_BookId_idx` (`FavBook` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  CONSTRAINT `Fk_BookId_UserProfile`
    FOREIGN KEY (`FavBook`)
    REFERENCES `testdb`.`Book` (`GoogleBooksID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Review` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Comment` VARCHAR(300) NOT NULL,
  `Rating` TINYINT NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `Upvotes` INT NULL,
  `BookId` CHAR(12) NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_UserId_idx` (`UserId` ASC),
  INDEX `FK_BookId_idx` (`BookId` ASC),
  CONSTRAINT `FK_UserId_Review`
    FOREIGN KEY (`UserId`)
    REFERENCES `testdb`.`UserProfile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BookId_Review`
    FOREIGN KEY (`BookId`)
    REFERENCES `testdb`.`Book` (`GoogleBooksID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Bookshelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Bookshelf` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `IsDeletable` TINYINT NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_UserId_idx` (`UserId` ASC),
  CONSTRAINT `FK_UserId_Bookshelf`
    FOREIGN KEY (`UserId`)
    REFERENCES `testdb`.`UserProfile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Collection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Collection` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `IsPublic` TINYINT NOT NULL DEFAULT 0,
  `Upvotes` INT NULL,
  `BookId` CHAR(12) NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_BookId_idx` (`BookId` ASC),
  INDEX `FK_UserId_idx` (`UserId` ASC),
  CONSTRAINT `FK_BookId_Collection`
    FOREIGN KEY (`BookId`)
    REFERENCES `testdb`.`Book` (`GoogleBooksID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UserId_Collection`
    FOREIGN KEY (`UserId`)
    REFERENCES `testdb`.`UserProfile` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`Note` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Content` VARCHAR(300) NOT NULL,
  `CreationDate` DATETIME NOT NULL,
  `CollectionId` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `CollectionId_idx` (`CollectionId` ASC),
  CONSTRAINT `CollectionId`
    FOREIGN KEY (`CollectionId`)
    REFERENCES `testdb`.`Collection` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`BooksInBookshelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testdb`.`BooksInBookshelf` (
  `BookId` CHAR(12) NOT NULL,
  `BookshelfId` INT NOT NULL,
  `DateAdded` DATETIME NOT NULL,
  PRIMARY KEY (`BookId`, `BookshelfId`),
  INDEX `FK_BookshelfId_idx` (`BookshelfId` ASC),
  CONSTRAINT `FK_BookId_BooksInBookshelf`
    FOREIGN KEY (`BookId`)
    REFERENCES `testdb`.`Book` (`GoogleBooksID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BookshelfId_BooksInBookShelf`
    FOREIGN KEY (`BookshelfId`)
    REFERENCES `testdb`.`Bookshelf` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
